import { test, expect } from '@playwright/test'

for (const lang of ['zh', 'en']) {
  test(`built client: layout, comments, copy, settings and renderer delegation (${lang})`, async ({ page }) => {
    const errors = []; page.on('pageerror', error => errors.push(error.message))
    await page.goto(`/?lang=${lang}`)
    const surface = page.locator('#review-surface')
    await expect(surface.getByText('service.ts', { exact: true }).first()).toBeVisible()
    await surface.getByRole('button', { name: lang === 'zh' ? '展开本轮全部仓库的文件内容' : 'Expand file contents in all repositories in this turn' }).click()
    const diffs = surface.locator('[data-diff-layout]')
    await expect(diffs.first()).toHaveAttribute('data-diff-layout', 'split')
    await diffs.first().getByRole('button', { name: lang === 'zh' ? '搜索' : 'Search', exact: true }).click()
    const query = diffs.first().getByRole('searchbox')
    await query.fill('validate')
    await page.getByRole('button', { name: '400px', exact: true }).click()
    await expect(diffs.first()).toHaveAttribute('data-diff-layout', 'unified')
    await expect(query).toHaveValue('validate')
    expect(await page.evaluate(() => window.fixture.form.getSnapshot().value.reviewSettings.layout)).toBe('split')
    await page.getByRole('button', { name: '820px', exact: true }).click()
    await expect(diffs.first()).toHaveAttribute('data-diff-layout', 'split')
    const dock = page.locator('[data-review-comments-dock]')
    await dock.locator('summary').click()
    await expect(dock).toContainText('core')
    await dock.getByRole('button', { name: lang === 'zh' ? '随输入发送' : 'Send with input' }).click()
    await expect(page.locator('[data-input-reference]')).toBeVisible()
    await expect(page.locator('[data-input-prose]')).toContainText(lang === 'zh' ? '请保持现有接口。' : 'Keep the existing interface.')
    await expect(page.locator('[data-input-attachment]')).toBeVisible()
    await surface.getByRole('button', { name: lang === 'zh' ? '复制差异' : 'Copy differences', exact: true }).first().click()
    await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toContain('Multi-repository review report')
    const copied = await page.evaluate(() => navigator.clipboard.readText())
    expect(copied).toContain('D:/fixture/core'); expect(copied).toContain('D:/fixture/web')
    if (process.env.UPDATE_BROWSER_FIXTURE_SCREENSHOTS) await page.screenshot({ path: test.info().outputPath(`review-enhancements-${lang}.jpg`), type: 'jpeg', quality: 85, fullPage: true })
    await page.getByRole('button', { name: 'Profile', exact: true }).click()
    const settings = page.locator('#settings-surface')
    await settings.getByRole('combobox', { name: lang === 'zh' ? '差异布局' : 'Diff layout' }).selectOption('unified')
    expect(await page.evaluate(() => window.fixture.form.getSnapshot().value.reviewSettings.layout)).toBe('unified')
    await settings.getByRole('button', { name: lang === 'zh' ? '设置' : 'Settings', exact: true }).click()
    const dialog = page.getByRole('dialog')
    await expect(dialog.getByLabel(lang === 'zh' ? '窄栏自动使用统一布局' : 'Use unified layout in narrow panels')).toBeChecked()
    if (process.env.UPDATE_BROWSER_FIXTURE_SCREENSHOTS) await page.screenshot({ path: test.info().outputPath(`profile-settings-${lang}.jpg`), type: 'jpeg', quality: 85 })
    await dialog.getByRole('button', { name: lang === 'zh' ? '取消' : 'Cancel', exact: true }).click()
    await page.getByRole('button', { name: 'Messages', exact: true }).click()
    await expect(page.locator('[data-review-packet]')).toBeVisible()
    await expect(page.locator('[data-host-attachment]')).toBeVisible()
    await expect(page.locator('[data-host-edit]').first()).toBeVisible()
    await expect(page.locator('[data-host-message]').last()).toContainText('Ordinary steering message')
    await page.locator('[data-review-packet] summary').click()
    await page.getByRole('button', { name: lang === 'zh' ? '复制完整审查信息' : 'Copy complete review information', exact: true }).click()
    await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toContain('<dsh_review')
    if (process.env.UPDATE_BROWSER_FIXTURE_SCREENSHOTS) await page.screenshot({ path: test.info().outputPath(`review-packet-${lang}.jpg`), type: 'jpeg', quality: 85 })
    await page.getByRole('button', { name: 'Toggle fixture message', exact: true }).click()
    await expect(page.locator('[data-review-packet]')).toHaveCount(0)
    await expect(page.locator('[data-host-message] strong')).toHaveText('Markdown')
    await dock.getByRole('button', { name: lang === 'zh' ? '清空待提交意见' : 'Clear pending comments', exact: true }).click()
    await expect(page.locator('[data-input-reference]')).toHaveCount(0)
    await expect(page.locator('[data-input-prose]')).toBeVisible()
    await page.evaluate(() => window.fixture.unmount())
    expect(await page.evaluate(() => window.fixture.seats.size)).toBe(0)
    expect(errors).toEqual([])
  })
  test(`built-in guide uses shipped images and official Markdown/lightbox (${lang})`, async ({ page }) => {
    await page.goto(`/?lang=${lang}`)
    await page.getByRole('button', { name: lang === 'zh' ? '操作指南' : 'User guide', exact: true }).click()
    const dialog = page.getByRole('dialog').first()
    await expect(dialog).toContainText(lang === 'zh' ? '文件审查插件使用手册' : 'File Review Plugin User Guide')
    const image = dialog.locator('img').first()
    await expect(image).toBeVisible()
    expect(await image.evaluate(element => element.complete && element.naturalWidth > 0)).toBe(true)
    await image.click()
    await expect(page.getByRole('dialog')).toHaveCount(2)
    await page.keyboard.press('Escape')
    await expect(page.getByRole('dialog')).toHaveCount(1)
    const chapters = dialog.getByRole('combobox', { name: lang === 'zh' ? '跳转章节' : 'Jump to chapter' })
    await expect(chapters.locator('option')).toHaveCount(21)
    const lastChapter = lang === 'zh' ? '20. 复制本轮／仓库差异' : '20. Copy a turn or repository'
    await chapters.selectOption({ label: lastChapter })
    const lastHeading = dialog.getByRole('heading', { name: lastChapter, exact: true })
    await expect(lastHeading).toBeInViewport()
    const firstChapter = lang === 'zh' ? '1. 插件能做什么' : '1. What the plugin does'
    await chapters.selectOption({ label: firstChapter })
    await expect(dialog.getByRole('heading', { name: firstChapter, exact: true })).toBeInViewport()
    await page.keyboard.press('Escape')
    await expect(page.getByRole('dialog')).toHaveCount(0)
  })
}
